// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';
import {instance} from '../models';
import {cmd} from '../models';

export function AddLocalRuntime(arg1:string):Promise<runtime.LlamaRuntime>;

export function BaseDir():Promise<string>;

export function CheckRuntime(arg1:string):Promise<Array<string>>;

export function ClearLogs(arg1:string):Promise<void>;

export function CreateInstance(arg1:instance.LlamaInstance):Promise<instance.LlamaInstance>;

export function DeleteInstance(arg1:string):Promise<void>;

export function DeleteOrphanRuntime(arg1:string):Promise<void>;

export function DownloadRuntime(arg1:string,arg2:string):Promise<runtime.LlamaRuntime>;

export function ExplainCommand(arg1:instance.LlamaInstance):Promise<Array<cmd.Explanation>>;

export function FetchAvailableReleases():Promise<Array<runtime.Release>>;

export function GetInstanceState(arg1:string):Promise<instance.InstanceState>;

export function GetInstanceStates():Promise<Array<instance.InstanceState>>;

export function GetLogs(arg1:string):Promise<Array<instance.LogLine>>;

export function GetRuntime(arg1:string):Promise<runtime.LlamaRuntime>;

export function GetRuntimeParams(arg1:string):Promise<Array<runtime.ParamDef>>;

export function ListInstances():Promise<Array<instance.LlamaInstance>>;

export function ListOrphanRuntimes():Promise<Array<runtime.OrphanDir>>;

export function ListRuntimes():Promise<Array<runtime.LlamaRuntime>>;

export function ParseCommand(arg1:string,arg2:string):Promise<cmd.ParsedCommand>;

export function PreviewCommand(arg1:instance.LlamaInstance):Promise<string>;

export function RemoveRuntime(arg1:string):Promise<void>;

export function RepairRuntime(arg1:string):Promise<runtime.LlamaRuntime>;

export function RestartInstance(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function StartInstance(arg1:string):Promise<void>;

export function StopInstance(arg1:string):Promise<void>;

export function UpdateInstance(arg1:instance.LlamaInstance):Promise<void>;
