// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLocalRuntime(arg1) {
  return window['go']['main']['App']['AddLocalRuntime'](arg1);
}

export function BaseDir() {
  return window['go']['main']['App']['BaseDir']();
}

export function CheckRuntime(arg1) {
  return window['go']['main']['App']['CheckRuntime'](arg1);
}

export function ClearLogs(arg1) {
  return window['go']['main']['App']['ClearLogs'](arg1);
}

export function CreateInstance(arg1) {
  return window['go']['main']['App']['CreateInstance'](arg1);
}

export function DeleteInstance(arg1) {
  return window['go']['main']['App']['DeleteInstance'](arg1);
}

export function DeleteOrphanRuntime(arg1) {
  return window['go']['main']['App']['DeleteOrphanRuntime'](arg1);
}

export function DownloadRuntime(arg1, arg2) {
  return window['go']['main']['App']['DownloadRuntime'](arg1, arg2);
}

export function ExplainCommand(arg1) {
  return window['go']['main']['App']['ExplainCommand'](arg1);
}

export function FetchAvailableReleases() {
  return window['go']['main']['App']['FetchAvailableReleases']();
}

export function GetInstanceState(arg1) {
  return window['go']['main']['App']['GetInstanceState'](arg1);
}

export function GetInstanceStates() {
  return window['go']['main']['App']['GetInstanceStates']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetRuntime(arg1) {
  return window['go']['main']['App']['GetRuntime'](arg1);
}

export function GetRuntimeParams(arg1) {
  return window['go']['main']['App']['GetRuntimeParams'](arg1);
}

export function ListInstances() {
  return window['go']['main']['App']['ListInstances']();
}

export function ListOrphanRuntimes() {
  return window['go']['main']['App']['ListOrphanRuntimes']();
}

export function ListRuntimes() {
  return window['go']['main']['App']['ListRuntimes']();
}

export function ParseCommand(arg1, arg2) {
  return window['go']['main']['App']['ParseCommand'](arg1, arg2);
}

export function PreviewCommand(arg1) {
  return window['go']['main']['App']['PreviewCommand'](arg1);
}

export function RemoveRuntime(arg1) {
  return window['go']['main']['App']['RemoveRuntime'](arg1);
}

export function RepairRuntime(arg1) {
  return window['go']['main']['App']['RepairRuntime'](arg1);
}

export function RestartInstance(arg1) {
  return window['go']['main']['App']['RestartInstance'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}

export function UpdateInstance(arg1) {
  return window['go']['main']['App']['UpdateInstance'](arg1);
}
